/*
  WebUI C++ Starter Kit - UI packer (build-time host tool)

  Packs every file inside a folder into a single C header (a tiny virtual
  file system), so the final executable embeds the whole UI.

      Usage: vfs <ui_folder> <output_header>

  The generated header exposes:

      static const void* vfs(const char* filename, int* length);

  which serves an embedded file as a full HTTP response, or returns NULL
  when the path is not an embedded file. It is used by http_handler() in
  src/main.cpp.

  This tool is compiled and executed automatically by the Makefile /
  GNUmakefile on every build - you never run it manually.
*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
	#include <windows.h>
#else
	#include <dirent.h>
	#include <sys/stat.h>
#endif

#define MAX_FILES 4096
#define MAX_PATH_LEN 512

typedef struct {
	char disk[MAX_PATH_LEN]; // Path on disk
	char url[MAX_PATH_LEN];  // Served path, without the leading slash
} pack_entry;

static pack_entry entries[MAX_FILES];
static int entries_count = 0;

static void add_entry(const char* disk, const char* url) {
	if (entries_count >= MAX_FILES) {
		fprintf(stderr, "vfs: too many files (max %d)\n", MAX_FILES);
		exit(1);
	}
	strcpy(entries[entries_count].disk, disk);
	strcpy(entries[entries_count].url, url);
	entries_count++;
}

// Recursively collect all files inside `dir`. `rel` is the URL-style
// relative path: "" at the root, then "sub" / "sub/dir" ...
static void walk(const char* dir, const char* rel) {
	char disk[MAX_PATH_LEN];
	char url[MAX_PATH_LEN];
#ifdef _WIN32
	char pattern[MAX_PATH_LEN];
	WIN32_FIND_DATAA fd;
	HANDLE h;
	if (snprintf(pattern, sizeof(pattern), "%s\\*", dir) >= (int)sizeof(pattern)) return;
	h = FindFirstFileA(pattern, &fd);
	if (h == INVALID_HANDLE_VALUE) return;
	do {
		if (strcmp(fd.cFileName, ".") == 0 || strcmp(fd.cFileName, "..") == 0) continue;
		if (snprintf(disk, sizeof(disk), "%s\\%s", dir, fd.cFileName) >= (int)sizeof(disk)) continue;
		if (rel[0] != '\0') {
			if (snprintf(url, sizeof(url), "%s/%s", rel, fd.cFileName) >= (int)sizeof(url)) continue;
		} else {
			if (snprintf(url, sizeof(url), "%s", fd.cFileName) >= (int)sizeof(url)) continue;
		}
		if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) walk(disk, url);
		else add_entry(disk, url);
	} while (FindNextFileA(h, &fd));
	FindClose(h);
#else
	DIR* d = opendir(dir);
	struct dirent* de;
	struct stat st;
	if (d == NULL) return;
	while ((de = readdir(d)) != NULL) {
		if (strcmp(de->d_name, ".") == 0 || strcmp(de->d_name, "..") == 0) continue;
		if (snprintf(disk, sizeof(disk), "%s/%s", dir, de->d_name) >= (int)sizeof(disk)) continue;
		if (rel[0] != '\0') {
			if (snprintf(url, sizeof(url), "%s/%s", rel, de->d_name) >= (int)sizeof(url)) continue;
		} else {
			if (snprintf(url, sizeof(url), "%s", de->d_name) >= (int)sizeof(url)) continue;
		}
		if (stat(disk, &st) != 0) continue;
		if (S_ISDIR(st.st_mode)) walk(disk, url);
		else if (S_ISREG(st.st_mode)) add_entry(disk, url);
	}
	closedir(d);
#endif
}

static int cmp_entry(const void* a, const void* b) {
	return strcmp(((const pack_entry*)a)->url, ((const pack_entry*)b)->url);
}

int main(int argc, char* argv[]) {

	if (argc != 3) {
		fprintf(stderr, "Usage: %s <ui_folder> <output_header>\n", argv[0]);
		return 1;
	}
	const char* input = argv[1];
	const char* output = argv[2];

	walk(input, "");
	if (entries_count == 0)
		fprintf(stderr, "vfs: warning: no files found in '%s'\n", input);

	// Deterministic output order
	qsort(entries, (size_t)entries_count, sizeof(pack_entry), cmp_entry);

	FILE* out = fopen(output, "w");
	if (out == NULL) {
		fprintf(stderr, "vfs: cannot write '%s'\n", output);
		return 1;
	}

	fprintf(out,
		"// Generated by tools/vfs.c - DO NOT EDIT\n"
		"// Regenerated on every build from the '%s' folder\n\n"
		"#ifndef WEBUI_STARTER_KIT_VFS_H\n"
		"#define WEBUI_STARTER_KIT_VFS_H\n\n"
		"#include <stdio.h>\n"
		"#include <string.h>\n"
		"#include \"webui.h\"\n\n"
		"typedef struct {\n"
		"    const char *path;\n"
		"    const unsigned char *data;\n"
		"    int length;\n"
		"} VirtualFile;\n\n", input);

	// File data arrays
	long* sizes = (long*)calloc((size_t)(entries_count > 0 ? entries_count : 1), sizeof(long));
	if (sizes == NULL) {
		fprintf(stderr, "vfs: out of memory\n");
		fclose(out);
		return 1;
	}
	for (int i = 0; i < entries_count; i++) {
		FILE* f = fopen(entries[i].disk, "rb");
		if (f == NULL) {
			fprintf(stderr, "vfs: cannot read '%s'\n", entries[i].disk);
			fclose(out);
			return 1;
		}
		fprintf(out, "static const unsigned char FILE_%d[] = {", i);
		unsigned char buf[4096];
		size_t n;
		long written = 0;
		while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
			for (size_t j = 0; j < n; j++) {
				if ((written % 20) == 0) fputs("\n    ", out);
				fprintf(out, "0x%02x,", buf[j]);
				written++;
			}
		}
		fclose(f);
		// Trailing NUL (not counted in length): lets text files be used as C strings
		fputs("0x00", out);
		sizes[i] = written;
		fputs("\n};\n\n", out);
	}

	// File table
	fputs("static const VirtualFile virtual_files[] = {\n", out);
	for (int i = 0; i < entries_count; i++)
		fprintf(out, "    {\"/%s\", FILE_%d, %ld},\n", entries[i].url, i, sizes[i]);
	if (entries_count == 0)
		fputs("    {NULL, NULL, 0},\n", out);
	fputs("};\n\n", out);
	fputs("static const int virtual_files_count = (int)(sizeof(virtual_files) / sizeof(virtual_files[0]));\n\n", out);

	// The vfs() lookup used by http_handler() in src/main.cpp
	fputs(
		"// Serves an embedded file as a full HTTP response.\n"
		"// Returns NULL when `filename` is not an embedded file.\n"
		"static const void* vfs(const char* filename, int* length) {\n"
		"    for (int i = 0; i < virtual_files_count; i++) {\n"
		"        if (virtual_files[i].path != NULL && strcmp(virtual_files[i].path, filename) == 0) {\n"
		"            const unsigned char* file_data = virtual_files[i].data;\n"
		"            int file_length = virtual_files[i].length;\n"
		"            const char* content_type = webui_get_mime_type(filename);\n"
		"            const char* http_header_template = \"HTTP/1.1 200 OK\\r\\n\"\n"
		"                                               \"Content-Type: %s\\r\\n\"\n"
		"                                               \"Content-Length: %d\\r\\n\"\n"
		"                                               \"Cache-Control: no-cache\\r\\n\\r\\n\";\n"
		"            int header_length = snprintf(NULL, 0, http_header_template, content_type, file_length);\n"
		"            *length = header_length + file_length;\n"
		"            unsigned char* response = (unsigned char*)webui_malloc((size_t)*length + 1);\n"
		"            snprintf((char*)response, (size_t)header_length + 1, http_header_template, content_type, file_length);\n"
		"            memcpy(response + header_length, file_data, (size_t)file_length);\n"
		"            return response;\n"
		"        }\n"
		"    }\n"
		"    return NULL;\n"
		"}\n"
		"\n"
		"#endif // WEBUI_STARTER_KIT_VFS_H\n", out);

	free(sizes);
	fclose(out);
	printf("vfs: embedded %d file(s) from '%s' into '%s'\n", entries_count, input, output);
	return 0;
}
