# http://webui.me
# https://github.com/webui-dev/webui
# Copyright (c) 2020-2024 Hassan Draga.
# Licensed under MIT License.
# All rights reserved.
#
# WebUI JavaScript to C Header

def js_to_c_header(input_filename, output_filename):
    try:
        # Read JS file content
        with open(input_filename, 'r', encoding='utf-8') as f:
            content = f.read()

        print(f"Converting '{input_filename}' to '{output_filename}'...")

        # Convert each character in JS content to its hexadecimal value
        hex_values = ["0x{:02x}".format(ord(char)) for char in content]

        # Prepare the content for the C header file
        header_content = (
            "// --- PLEASE DO NOT EDIT THIS FILE -------\n"
            "// --- THIS FILE IS GENERATED BY JS2C.PY --\n\n"
            "#ifndef WEBUI_BRIDGE_H\n"
            "#define WEBUI_BRIDGE_H\n"
            "unsigned char webui_javascript_bridge[] = { "
        )

        # Split the hexadecimal values to make the output more readable, adding a new line every 10 values
        for i in range(0, len(hex_values), 10):
            header_content += "\n    " + ', '.join(hex_values[i:i+10]) + ','

        header_content += "\n    0x00\n};\n\n#endif // WEBUI_BRIDGE_H"

        # Write the header content to the output file
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write(header_content)

    except FileNotFoundError:
        print(f"Error: File '{input_filename}' not found.")
        return

# Main
js_to_c_header('webui.js', 'webui_bridge.h')
